services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Montre le socket Docker
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - nmap_worker
      - nuclei_worker
      - nikto_worker
      - subfinder_worker

  nmap_worker:
    build:
      context: ./workers/nmap
    entrypoint: ["nmap"]

  nuclei_worker:
    build:
      context: ./workers/nuclei
    entrypoint: ["nuclei"]

  nikto_worker:
    build:
      context: ./workers/nikto
    entrypoint: ["nikto"]

  subfinder_worker:
    build:
      context: ./workers/subfinder
    entrypoint: ["subfinder"]